### ISSUE TITLE
Google Play Service crashes upon install app

### ISSUE THREAD

**Issue by k0shk0sh** [firebase/firebase-jobdispatcher-android#116]
Hello there, 

It brings to my attention that some people reported bugs that upon installing my app from the play store, it will immediately crashes Google Play service & it will crash any other apps that might rely on the google play service.

Please find the attached log below from the play store from the same device as the video below shows:

[crash.txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1059869/crash.txt)

and also find the video for your referencing, its a video from a user that reported this via email

https://drive.google.com/file/d/0BxbjAF1sbwjaV245MGl0Z054bGM/view?usp=sharing

Please do let me know if there is any workaround this like immediate workaround, otherwise i'll just have to drop firebase dispatcher immediately to solve this.

**Comment by k0shk0sh** [comment]
dropping Firebase job dispatcher unfortunately  didn't work, still hitting the same crash.

**Comment by ogeidix** [comment]
Hi @k0shk0sh 
thanks for your report.
Unfortunately the logs don't contain helpful information.
Any chance you can ask for a bugreport from the device where this is happening?

**Comment by k0shk0sh** [comment]
@ogeidix here you go
```
Fatal Exception: java.lang.RuntimeException: Unable to unbind to service com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask@18697b9 with Intent { act=com.firebase.jobdispatcher.ACTION_EXECUTE cmp=com.fastaccess.github/com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3285)
       at android.app.ActivityThread.-wrap28(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
       at android.os.Message.sendToTarget(Message.java:416)
       at com.firebase.jobdispatcher.JobService$JobCallback.sendResult(JobService.java:230)
       at com.firebase.jobdispatcher.JobService.onUnbind(JobService.java:177)
       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3271)
       at android.app.ActivityThread.-wrap28(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by k0shk0sh** [comment]
Here is a longer file

[com.fastaccess.github_issue_26_crash_5945543A0124000179EEDF6E642A57D5_004fa0d1538a11e79f1e56847afe9799_0_v2 (1).txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1082696/com.fastaccess.github_issue_26_crash_5945543A0124000179EEDF6E642A57D5_004fa0d1538a11e79f1e56847afe9799_0_v2.1.txt)

**Comment by ogeidix** [comment]
That is the crash in your app which seems to happen because Play services crashed.
We can avoid crashing in Firebase Job Dispatcher, but even better would be to fix the crash in Play services.
If you could get a full bugreport (via "adb bugreport" or developer settings) we could see why Play services is crashing.

**Comment by k0shk0sh** [comment]
I have asked the user to do that, because I can't simulate that problem. so I guess we gotta wait on this.

**Comment by k0shk0sh** [comment]
@ogeidix end user couldn't do that because as soon as installing FastHub, his system starts to crash and can't go anywhere but playstore and uninstall it from there. i'm a bit lost here and don't know what should be done

**Comment by ogeidix** [comment]
they can take the bugreport after the uninstalled the app. the logs should still be captured by the bugreport

**Comment by k0shk0sh** [comment]
[bugreport-2017-07-11-07-15-55.txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1137919/bugreport-2017-07-11-07-15-55.txt)
@ogeidix here is the bug report as requested

**Comment by unEgor** [comment]
Thank you for the bug report.
Unfortunately it does not contain any information regarding the crash.
Could you please switch to new version 0.7.0 and try to reproduce it?

I've check the code and I don't know how it could happen.
The message is created it ExecutionDelegator.executeJob -> "responseHandler.obtainMessage(JOB_FINISHED)"
responseHandler is the target in the message. So the message can't be created in the first place.

You might modify message target by calling setTarget on the message.

**Comment by k0shk0sh** [comment]
@unEgor  below another report from the same user which tested on 0.7.0 but still have the same problem.  why not just catch the crash from within the jobDispatcher itself? would that possible without me cloning the repo?


[bugreport-2017-07-13-11-52-43.txt](https://github.com/firebase/firebase-jobdispatcher-android/files/1144787/bugreport-2017-07-13-11-52-43.txt)

**Comment by unEgor** [comment]
Thank you for the bugreport and using 0.7.0 version.

From the bug report I does not look like there are any problem with FJD.
I think the issue is related to Android. 
https://stackoverflow.com/questions/4740530/unable-to-launch-app-for-broadcast-intent
https://stackoverflow.com/questions/3253676/how-to-fix-process-is-bad-error-for-an-android-widget

07-13 11:45:45.801   484   881 W BroadcastQueue: Unable to launch app com.teslacoilsw.launcher/10064 for broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.fastaccess.github flg=0x4000010 (has extras) }:  process is bad
....
07-13 11:49:08.915   484   519 D PackageManager: Renaming /data/app/vmdl1170361275.tmp to /data/app/com.fastaccess.github.debug-1
07-13 11:49:58.280   484   484 D BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.fastaccess.github.debug flg=0x4000010 (has extras) }
07-13 11:49:58.659 18740 18760 F libc    : invalid address or address of corrupt block 0x3b passed to dlfree
07-13 11:49:58.659 18740 18760 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 18760 (launcher-loader)
07-13 11:49:58.762 24719 24719 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by k0shk0sh** [comment]
@unEgor hmmm, I have zero broadcast receivers in FastHub so I'm not really sure how this could be related, if you look at video above, you'll see every app is crashing and because the GooglePlayService so I'm sure nova broadcast receiver crashed because of firebase & google play service. 

P.S: the broadcast that shows in the log is tied to nova launcher.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ogeidix** [comment]
From the full bugreport you provided it doesn't look like it's Google Play services crashing, but rather the whole system.

I suspect this is a bug in cyanogenmod.
The bugreport seems to suggest some crash in cyanogenmod theme component.

```
07-10 00:31:36.493   484   519 D PackageManager: /data/app/vmdl1524415148.tmp already staged; skipping copy
07-10 00:31:37.922   484   519 D PackageManager: Renaming /data/app/vmdl1524415148.tmp to /data/app/com.fastaccess.github-1
07-10 00:32:00.933   484   484 D BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.fastaccess.github flg=0x4000010 (has extras) }
07-10 00:32:01.050   484   484 W BackupManagerService: Removing schedule queue dupe of com.fastaccess.github
07-10 00:32:01.763 19595 19595 F libc    : invalid address or address of corrupt block 0x29 passed to dlfree
07-10 00:32:01.763 19595 19595 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 19595 (themes.provider)
07-10 00:32:02.135   137   137 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-10 00:32:02.135   137   137 I DEBUG   : Build fingerprint: 'google/nakasi/grouper:5.1/LMY47D/1743759:user/release-keys'
07-10 00:32:02.135   137   137 I DEBUG   : Revision: '0'
07-10 00:32:02.135   137   137 I DEBUG   : ABI: 'arm'
07-10 00:32:02.135   137   137 I DEBUG   : pid: 19595, tid: 19595, name: themes.provider  >>> org.cyanogenmod.themes.provider <<<
07-10 00:32:02.135   137   137 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
07-10 00:32:02.338   137   137 I DEBUG   : Abort message: 'invalid address or address of corrupt block 0x29 passed to dlfree'
07-10 00:32:02.338   137   137 I DEBUG   :     r0 00000000  r1 40175dec  r2 deadbaad  r3 00000000
07-10 00:32:02.338   137   137 I DEBUG   :     r4 00000029  r5 401770d8  r6 40001000  r7 00000031
07-10 00:32:02.338   137   137 I DEBUG   :     r8 be9b9acc  r9 be9b9b8c  sl 402232aa  fp 402232b3
07-10 00:32:02.338   137   137 I DEBUG   :     ip 00008000  sp be9b9a78  lr 4014720b  pc 4014720c  cpsr 600b0030
07-10 00:32:02.338   137   137 I DEBUG   : 
07-10 00:32:02.338   137   137 I DEBUG   : backtrace:
07-10 00:32:02.338   137   137 I DEBUG   :     #00 pc 0002920c  /system/lib/libc.so (dlfree+1239)
07-10 00:32:02.338   137   137 I DEBUG   :     #01 pc 0000f363  /system/lib/libc.so (free+10)
07-10 00:32:02.339   137   137 I DEBUG   :     #02 pc 00012b37  /system/lib/libandroidfw.so (_ZN7android13ResStringPool6uninitEv+38)
07-10 00:32:02.339   137   137 I DEBUG   :     #03 pc 00013873  /system/lib/libandroidfw.so (_ZN7android10ResXMLTree6uninitEv+12)
07-10 00:32:02.339   137   137 I DEBUG   :     #04 pc 00013891  /system/lib/libandroidfw.so (_ZN7android10ResXMLTreeD1Ev+4)
07-10 00:32:02.339   137   137 I DEBUG   :     #05 pc 00010557  /system/lib/libandroidfw.so (_ZN7android12AssetManager10getPkgNameEPKc+258)
07-10 00:32:02.339   137   137 I DEBUG   :     #06 pc 000105b9  /system/lib/libandroidfw.so (_ZN7android12AssetManager18getBasePackageNameEj+68)
07-10 00:32:02.339   137   137 I DEBUG   :     #07 pc 0008200f  /system/lib/libandroid_runtime.so
07-10 00:32:02.339   137   137 I DEBUG   :     #08 pc 0027b473  /data/dalvik-cache/arm/system@framework@boot.oat
07-10 00:32:02.675 22322 22322 F libc    : invalid address or address of corrupt block 0x49 passed to dlfree
07-10 00:32:02.675 22322 22322 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 22322 (android.vending)
07-10 00:32:03.705   137   137 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-10 00:32:03.706   137   137 I DEBUG   : Build fingerprint: 'google/nakasi/grouper:5.1/LMY47D/1743759:user/release-keys'
07-10 00:32:03.706   137   137 I DEBUG   : Revision: '0'
07-10 00:32:03.706   137   137 I DEBUG   : ABI: 'arm'
07-10 00:32:03.706   137   137 I DEBUG   : pid: 22322, tid: 22322, name: android.vending  >>> com.android.vending <<<
07-10 00:32:03.707   137   137 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
07-10 00:32:03.731   137   137 I DEBUG   : Abort message: 'invalid address or address of corrupt block 0x49 passed to dlfree'
07-10 00:32:03.732   137   137 I DEBUG   :     r0 00000000  r1 40175dec  r2 deadbaad  r3 00000000
07-10 00:32:03.732   137   137 I DEBUG   :     r4 00000049  r5 401770d8  r6 40000000  r7 00000051
07-10 00:32:03.732   137   137 I DEBUG   :     r8 be9b9bbc  r9 be9b9c7c  sl 402232aa  fp 402232b3
07-10 00:32:03.732   137   137 I DEBUG   :     ip 00008000  sp be9b9b68  lr 4014720b  pc 4014720c  cpsr 60030030
07-10 00:32:03.732   137   137 I DEBUG   : 
07-10 00:32:03.732   137   137 I DEBUG   : backtrace:
07-10 00:32:03.733   137   137 I DEBUG   :     #00 pc 0002920c  /system/lib/libc.so (dlfree+1239)
07-10 00:32:03.733   137   137 I DEBUG   :     #01 pc 0000f363  /system/lib/libc.so (free+10)
07-10 00:32:03.733   137   137 I DEBUG   :     #02 pc 00012b37  /system/lib/libandroidfw.so (_ZN7android13ResStringPool6uninitEv+38)
07-10 00:32:03.733   137   137 I DEBUG   :     #03 pc 00013873  /system/lib/libandroidfw.so (_ZN7android10ResXMLTree6uninitEv+12)
07-10 00:32:03.733   137   137 I DEBUG   :     #04 pc 00013891  /system/lib/libandroidfw.so (_ZN7android10ResXMLTreeD1Ev+4)
07-10 00:32:03.733   137   137 I DEBUG   :     #05 pc 00010557  /system/lib/libandroidfw.so (_ZN7android12AssetManager10getPkgNameEPKc+258)
07-10 00:32:03.733   137   137 I DEBUG   :     #06 pc 000105b9  /system/lib/libandroidfw.so (_ZN7android12AssetManager18getBasePackageNameEj+68)
07-10 00:32:03.734   137   137 I DEBUG   :     #07 pc 0008200f  /system/lib/libandroid_runtime.so
07-10 00:32:03.734   137   137 I DEBUG   :     #08 pc 0027b473  /data/dalvik-cache/arm/system@framework@boot.oat
07-10 00:32:03.775   484   509 I BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
07-10 00:32:03.870   484   666 I ActivityManager: Process org.cyanogenmod.themes.provider (pid 19595) has died
07-10 00:32:03.870   484   666 D ActivityManager: cleanUpApplicationRecord -- 19595
07-10 00:32:03.944   484   506 I ActivityManager: Start proc 24343:com.google.android.partnersetup/u0a56 for broadcast com.google.android.partnersetup/.RlzPingBroadcastReceiver
07-10 00:32:05.246 23528 23549 F libc    : invalid address or address of corrupt block 0x250 passed to dlfree
07-10 00:32:05.249 23528 23549 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 23549 (launcher-loader)
07-10 00:32:05.382   484  2224 I ActivityManager: Start proc 24367:com.svox.pico/u0a45 for broadcast com.svox.pico/.VoiceDataInstallerReceiver
07-10 00:32:05.785   484   638 E NativeCrashListener: Exception dealing with report
07-10 00:32:05.785   484   638 E NativeCrashListener: android.system.ErrnoException: read failed: EAGAIN (Try again)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at libcore.io.Posix.readBytes(Native Method)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at libcore.io.Posix.read(Posix.java:165)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at android.system.Os.read(Os.java:350)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
07-10 00:32:05.785   484   638 E NativeCrashListener: 	at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
07-10 00:32:09.346  7632  7944 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0x654d2e70 in tid 7944 (lowpool[1])
07-10 00:32:09.965   484   509 I BootReceiver: Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
07-10 00:32:10.030   484  1941 I WindowState: WIN DEATH: Window{19b9208a u0 com.android.vending/com.google.android.finsky.activities.ReviewsActivity}
07-10 00:32:10.034   137   137 I DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-10 00:32:10.034   137   137 I DEBUG   : Build fingerprint: 'google/nakasi/grouper:5.1/LMY47D/1743759:user/release-keys'
07-10 00:32:10.034   137   137 I DEBUG   : Revision: '0'
07-10 00:32:10.034   137   137 I DEBUG   : ABI: 'arm'
07-10 00:32:10.034   137   137 I DEBUG   : pid: 23528, tid: 23549, name: launcher-loader  >>> com.cyanogenmod.trebuchet <<<
07-10 00:32:10.034   137   137 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
07-10 00:32:10.035   484  1908 I WindowState: WIN DEATH: Window{6367d90 u0 com.android.vending/com.google.android.finsky.activities.MainActivity}
07-10 00:32:10.069   137   137 I DEBUG   : Abort message: 'invalid address or address of corrupt block 0x250 passed to dlfree'
07-10 00:32:10.070   137   137 I DEBUG   :     r0 00000000  r1 40175dec  r2 deadbaad  r3 00000000
07-10 00:32:10.070   137   137 I DEBUG   :     r4 00000250  r5 401770d8  r6 40000000  r7 00000258
07-10 00:32:10.070   137   137 I DEBUG   :     r8 6ad3542c  r9 6ad354ec  sl 402232aa  fp 402232b3
07-10 00:32:10.070   137   137 I DEBUG   :     ip 01000000  sp 6ad353d8  lr 4014720b  pc 4014720c  cpsr 60030030
07-10 00:32:10.071   137   137 I DEBUG   : 
07-10 00:32:10.071   137   137 I DEBUG   : backtrace:
07-10 00:32:10.071   137   137 I DEBUG   :     #00 pc 0002920c  /system/lib/libc.so (dlfree+1239)
07-10 00:32:10.071   137   137 I DEBUG   :     #01 pc 0000f363  /system/lib/libc.so (free+10)
07-10 00:32:10.071   137   137 I DEBUG   :     #02 pc 00012b37  /system/lib/libandroidfw.so (_ZN7android13ResStringPool6uninitEv+38)
07-10 00:32:10.071   137   137 I DEBUG   :     #03 pc 00013873  /system/lib/libandroidfw.so (_ZN7android10ResXMLTree6uninitEv+12)
07-10 00:32:10.071   137   137 I DEBUG   :     #04 pc 00013891  /system/lib/libandroidfw.so (_ZN7android10ResXMLTreeD1Ev+4)
07-10 00:32:10.072   137   137 I DEBUG   :     #05 pc 00010557  /system/lib/libandroidfw.so (_ZN7android12AssetManager10getPkgNameEPKc+258)
07-10 00:32:10.072   137   137 I DEBUG   :     #06 pc 000105b9  /system/lib/libandroidfw.so (_ZN7android12AssetManager18getBasePackageNameEj+68)
07-10 00:32:10.072   137   137 I DEBUG   :     #07 pc 0008200f  /system/lib/libandroid_runtime.so
07-10 00:32:10.072   137   137 I DEBUG   :     #08 pc 0027b473  /data/dalvik-cache/arm/system@framework@boot.oat
07-10 00:32:10.182   484  2225 I ActivityManager: Process com.android.vending (pid 22322) has died
07-10 00:32:10.182   484  2225 D ActivityManager: cleanUpApplicationRecord -- 22322
07-10 00:32:10.182   484  2225 W ActivityManager: Force removing ActivityRecord{2ad0da83 u0 com.android.vending/com.google.android.finsky.activities.ReviewsActivity t1347}: app died, no saved state
07-10 00:32:10.196   484   512 V WindowManager: Adding window Window{11a8d9f3 u0 Starting com.android.vending} at 7 of 15 (before Window{19b9208a u0 com.android.vending/com.google.android.finsky.activities.ReviewsActivity EXITING})
07-10 00:32:10.257   484  2225 I ActivityManager: Start proc 24411:com.android.vending/u0a57 for activity com.android.vending/com.google.android.finsky.activities.MainActivity
07-10 00:32:11.649   484   509 I BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
07-10 00:32:11.681   484  1908 I WindowState: WIN DEATH: Window{e9ab962 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher}
07-10 00:32:11.822   484  2222 I ActivityManager: Process com.cyanogenmod.trebuchet (pid 23528) has died
07-10 00:32:11.822   484  2222 D ActivityManager: cleanUpApplicationRecord -- 23528

```

**Comment by k0shk0sh** [comment]
@ogeidix thanks man, I guess then I'll just ignore it. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ogeidix** [comment]
Yes, it's unfortunate but this looks like out of our control.
I would tell the user to check if they can update to a more recent version of cyanogenmod (maybe they fixed the bug in a following release).

**Comment by dmfs** [comment]
FTR, we had the same issue with our app. During my research I came across this report.
I also found this https://issuetracker.google.com/issues/64434571 which seems to confirm the problem in cyanogenmod but also states that build-tools 27 "fix" this issue. So if you see this issue, make sure you use the latest build-tools.
