### ISSUE TITLE
JobService doesn't start with serialazable and parcelable extra parameters

### ISSUE THREAD

**Issue by Buckstabue** [firebase/firebase-jobdispatcher-android#236]
If I start a job service with an extra serialazable parameter, it will silently be ignored, there is even no log message in logcat. If i start it with a parcelable parameter, I have my application crashed with such logs
```   java.lang.RuntimeException: Unable to start service com.firebase.jobdispatcher.GooglePlayReceiver@30ee0841 with Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.sebbia.youdo/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.youdo.ui.entity.vo.ChatNotificationVO
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
        at android.app.ActivityThread.access$2100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.youdo.ui.entity.vo.ChatNotificationVO
        at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
        at android.os.Parcel.readParcelable(Parcel.java:2245)
        at android.os.Parcel.readValue(Parcel.java:2152)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:621)
        at com.firebase.jobdispatcher.JobCoder.decode(JobCoder.java:103)
        at com.firebase.jobdispatcher.JobCoder.decodeIntentBundle(JobCoder.java:86)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:205)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:200)
        at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(GooglePlayReceiver.java:114)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
        at android.app.ActivityThread.access$2100(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) ```

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
