### ISSUE TITLE
GooglePlayReceiver BadParcelableException: ClassNotFoundException

### ISSUE THREAD

**Issue by gotama** [firebase/firebase-jobdispatcher-android#245]
Version - 0.8.5

I searched your issues and saw a closed issue #72 #74 so reopened this one

Also just saw this new issue so linking here for clarity #236 

Refactored class to be **Serializable**, **Parcelable** and even used the [Parceler Lib](https://github.com/johncarl81/parceler) but still same error.

`05-31 16:49:19.339 2115-3246/com.google.android.gms.persistent E/Parcel: Class not found when unmarshalling: org.thereachtrust.ecdc.data.sync.UserContentSyncState
    java.lang.ClassNotFoundException: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2508)
        at android.os.Parcel.readParcelable(Parcel.java:2462)
        at android.os.Parcel.readValue(Parcel.java:2365)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.BaseBundle.getString(BaseBundle.java:992)
        at uqn.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):12)
        at uqn.<init>(:com.google.android.gms@12521024@12.5.21 (040700-189987672):12)
        at uqn.<init>(:com.google.android.gms@12521024@12.5.21 (040700-189987672):3)
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):38)
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):9)
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):117)
        at upu.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672):3)
        at nsg.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672):27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at nya.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672))
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2508) 
        at android.os.Parcel.readParcelable(Parcel.java:2462) 
        at android.os.Parcel.readValue(Parcel.java:2365) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
        at android.os.BaseBundle.getString(BaseBundle.java:992) 
        at uqn.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):12) 
        at uqn.<init>(:com.google.android.gms@12521024@12.5.21 (040700-189987672):12) 
        at uqn.<init>(:com.google.android.gms@12521024@12.5.21 (040700-189987672):3) 
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):38) 
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):9) 
        at usa.a(:com.google.android.gms@12521024@12.5.21 (040700-189987672):117) 
        at upu.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672):3) 
        at nsg.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672):27) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at nya.run(:com.google.android.gms@12521024@12.5.21 (040700-189987672)) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-31 16:49:19.351 4546-4546/org.thereachtrust.careup E/Parcel: Class not found when unmarshalling: org.thereachtrust.ecdc.data.sync.UserContentSyncState
    java.lang.ClassNotFoundException: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2508)
        at android.os.Parcel.readParcelable(Parcel.java:2462)
        at android.os.Parcel.readValue(Parcel.java:2365)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:694)
        at com.firebase.jobdispatcher.JobCoder.decode(JobCoder.java:103)
        at com.firebase.jobdispatcher.JobCoder.decodeIntentBundle(JobCoder.java:86)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:205)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:200)
        at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(GooglePlayReceiver.java:114)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2508) 
        at android.os.Parcel.readParcelable(Parcel.java:2462) 
        at android.os.Parcel.readValue(Parcel.java:2365) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
        at android.os.BaseBundle.getBoolean(BaseBundle.java:694) 
        at com.firebase.jobdispatcher.JobCoder.decode(JobCoder.java:103) 
        at com.firebase.jobdispatcher.JobCoder.decodeIntentBundle(JobCoder.java:86) 
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:205) 
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:200) 
        at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(GooglePlayReceiver.java:114) 
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326) 
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-31 16:49:19.352 4546-4546/org.thereachtrust.careup E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thereachtrust.careup, PID: 4546
    java.lang.RuntimeException: Unable to start service com.firebase.jobdispatcher.GooglePlayReceiver@fa629b4 with Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=org.thereachtrust.careup/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3343)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.thereachtrust.ecdc.data.sync.UserContentSyncState
        at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
        at android.os.Parcel.readParcelable(Parcel.java:2462)
        at android.os.Parcel.readValue(Parcel.java:2365)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:694)
        at com.firebase.jobdispatcher.JobCoder.decode(JobCoder.java:103)
        at com.firebase.jobdispatcher.JobCoder.decodeIntentBundle(JobCoder.java:86)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:205)
        at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:200)
        at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(GooglePlayReceiver.java:114)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
