### ISSUE TITLE
Issue after reinvoking the job in background (after app was killed)

### ISSUE THREAD

**Issue by miraclebg** [firebase/firebase-jobdispatcher-android#254]
I'm getting the following exception (in background) after killing the app manually and having one scheduled notification.

Anything i am doing wrong or?

`07-10 12:59:15.029 1017-1772/com.google.android.gms.persistent E/NetworkScheduler.ATC: Trying to release unacquired lock: com.gymnadz/com.firebase.jobdispatcher.GooglePlayReceiver
07-10 12:59:15.030 11999-11999/com.gymnadz E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@437e93b that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@437e93b that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1514)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1406)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1589)
        at android.app.ContextImpl.bindService(ContextImpl.java:1541)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:678)
        at com.firebase.jobdispatcher.ExecutionDelegator.executeJob(ExecutionDelegator.java:110)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleStartMessage(GooglePlayMessageHandler.java:98)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleMessage(GooglePlayMessageHandler.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
