### ISSUE TITLE
RuntimeException: Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

### ISSUE THREAD

**Issue by skrabacz-michal** [firebase/firebase-jobdispatcher-android#255]
version: 0.8.5

Fatal Exception: java.lang.RuntimeException: Unable to unbind to service Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.support.v4.util.SimpleArrayMap.keyAt(SimpleArrayMap.java:370)
       at com.firebase.jobdispatcher.JobService.onUnbind(JobService.java:246)
       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3597)
       at android.app.ActivityThread.-wrap28(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
