### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.firebase.jobdispatcher.m.a

### ISSUE THREAD

**Issue by guytavor** [firebase/firebase-jobdispatcher-android#268]
We are using ``com.firebase:firebase-jobdispatcher:0.8.5``

We see a lot of crashes in our apps with the following stack trace:
``
Fatal Exception: java.lang.RuntimeException: Unable to start service com.firebase.jobdispatcher.GooglePlayReceiver@91f7fdb with Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.scoompa.slideshow/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'void com.firebase.jobdispatcher.m.a(android.os.Bundle, com.firebase.jobdispatcher.l)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
``
Any idea what's going on?

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
