### ISSUE TITLE
IllegalArgumentException: Service not registered: com.firebase.jobdispatcher.ExternalReceiver$JobServiceConnection

### ISSUE THREAD

**Issue by TheKeeperOfPie** [firebase/firebase-jobdispatcher-android#27]
ExternalReceiver crashes the application attempting to unbind a Service that is no longer alive. Seen this occur a few times just after running a new build from AndroidStudio, but not always, and not consistent enough to determine that's the actual cause. But since services can be killed for various reasons, I feel like ExternalReceiver should just try-catch this and not assume the service is live.

```
FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: Service not registered: com.firebase.jobdispatcher.ExternalReceiver$JobServiceConnection@5743276
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
    at com.firebase.jobdispatcher.ExternalReceiver.onJobFinishedMessage(ExternalReceiver.java:63)
    at com.firebase.jobdispatcher.ExternalReceiver.access$200(ExternalReceiver.java:41)
    at com.firebase.jobdispatcher.ExternalReceiver$ResponseHandler.handleMessage(ExternalReceiver.java:115)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ultramega** [comment]
PR #28 addresses this.
