### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: com.google.firebase.iid.zzk@c399ad3

### ISSUE THREAD

**Issue by liangdongbo** [firebase/firebase-jobdispatcher-android#287]
java.lang.IllegalArgumentException: Service not registered: com.google.firebase.iid.zzk@c399ad3
                                                                       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
                                                                       at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
                                                                       at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
                                                                       at com.google.firebase.iid.zzk.zzcjc(Unknown Source:50)
                                                                       at com.google.firebase.iid.zzk.zzd(Unknown Source:82)
                                                                       at com.google.firebase.iid.zzl.handleMessage(Unknown Source:2)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:201)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6806)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by emailsubjekt** [comment]
I don't want this to happen to me! I'm not going to use this!

**Comment by Magicsnail** [comment]
got same crash, how can i fix it?

**Comment by kkseay** [comment]
the same problem

**Comment by eLmistiso** [comment]
same  also

**Comment by MarkMjw** [comment]
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: g.k.b.g.h@5ae06
       at android.app.LoadedApk.forgetServiceDispatcher + 1671(LoadedApk.java:1671)
       at android.app.ContextImpl.unbindService + 1781(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService + 730(ContextWrapper.java:730)
       at com.google.android.gms.common.stats.ConnectionTracker.getInstance(ConnectionTracker.java)
       at com.google.firebase.iid.zzae.b + 48(zzae.java:48)
       at com.google.firebase.iid.zzae.a + 78(zzae.java:78)
       at com.google.firebase.iid.zzad.handleMessage + 2(zzad.java:2)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at com.google.android.gms.internal.firebase_messaging.zze.dispatchMessage(zze.java)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6981(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

**Comment by eLmistiso** [comment]
how to fix that sir?

**Comment by liangdongbo** [comment]
Prevent automatic initialization
AndroidManifest.xml
   <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="false" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />

**Comment by PatrickChoo** [comment]
It seems like this issue only affects this phone model in China, 73% happened in background.
Brand: OPPO Model: A9 中国版

**Comment by CrazyTrump** [comment]
same

**Comment by liangdongbo** [comment]
> 相同

Prevent automatic initialization
AndroidManifest.xml
   <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="false" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />

**Comment by liangdongbo** [comment]
> same

Prevent automatic initialization
AndroidManifest.xml
   <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="false" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />

**Comment by MarkMjw** [comment]
> > same
> 
> Prevent automatic initialization
> AndroidManifest.xml

@liangdongbo 你好，参考官方接入文档 https://firebase.google.com/docs/crashlytics/get-started?authuser=1&platform=android 还会报这个异常，有办法避免吗？

Fatal Exception: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1509)
       at android.app.ContextImpl.startService(ContextImpl.java:1486)
       at android.content.ContextWrapper.startService(ContextWrapper.java:624)
       at com.google.firebase.iid.zzau.zze(zzau.java:131)
       at com.google.firebase.iid.zzau.zzd(zzau.java:92)
       at com.google.firebase.iid.zzau.zzc(zzau.java:91)
       at com.google.firebase.iid.zzs.zza(zzs.java:78)
       at com.google.firebase.iid.zzr.run(zzr.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
