### ISSUE TITLE
I get the error log when app run in background long time(3 days)

### ISSUE THREAD

**Issue by xukai59740** [firebase/firebase-jobdispatcher-android#295]
2020-02-25 12:30:26.609 19145-19145/com.lionparcel.services.driver.stage W/FJD.ExternalReceiver: Error unbinding service: Service not registered: com.firebase.jobdispatcher.JobServiceConnection@4561150
2020-02-25 12:39:31.888 19145-19162/com.lionparcel.services.driver.stage W/es.driver.stag: Reducing the number of considered missed Gc histogram windows from 348 to 100
2020-02-25 12:41:21.263 19145-19145/com.lionparcel.services.driver.stage E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@fd65367 that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@fd65367 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1805)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1677)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1656)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1721)
        at android.app.ContextImpl.bindService(ContextImpl.java:1650)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
        at com.firebase.jobdispatcher.ExecutionDelegator.executeJob(ExecutionDelegator.java:110)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleStartMessage(GooglePlayMessageHandler.java:98)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleMessage(GooglePlayMessageHandler.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-02-25 12:41:21.266 19145-19145/com.lionparcel.services.driver.stage W/FJD.ExternalReceiver: Error unbinding service: Service not registered: com.firebase.jobdispatcher.JobServiceConnection@fd65367
2020-02-25 13:04:36.369 19145-19145/com.lionparcel.services.driver.stage E/ActivityThread: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@a50170a that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.firebase.jobdispatcher.GooglePlayReceiver has leaked ServiceConnection com.firebase.jobdispatcher.JobServiceConnection@a50170a that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1805)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1677)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1656)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1721)
        at android.app.ContextImpl.bindService(ContextImpl.java:1650)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
        at com.firebase.jobdispatcher.ExecutionDelegator.executeJob(ExecutionDelegator.java:110)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleStartMessage(GooglePlayMessageHandler.java:98)
        at com.firebase.jobdispatcher.GooglePlayMessageHandler.handleMessage(GooglePlayMessageHandler.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-02-25 13:04:36.375 19145-19145/com.lionparcel.services.driver.stage W/FJD.ExternalReceiver: Error unbinding service: Service not registered: com.firebase.jobdispatcher.JobServiceConnection@a50170a

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
