### ISSUE TITLE
Does not work with <null> extras in Bundle

### ISSUE THREAD

**Issue by michaeldiener** [firebase/firebase-jobdispatcher-android#49]
When using a null extra in my Bundle for the JobBuilder I get the following Exception:

```
com.firebase.jobdispatcher.ValidationEnforcer$ValidationException: JobParameters is invalid: Received value of type 'locationId' for key 'null', but only the following extra parameter types are supported: Integer, Long, Double, String, and Boolean
                                                                         at com.firebase.jobdispatcher.ValidationEnforcer.ensureNoErrors(ValidationEnforcer.java:113)
                                                                         at com.firebase.jobdispatcher.ValidationEnforcer.ensureValid(ValidationEnforcer.java:89)
                                                                         at com.firebase.jobdispatcher.Job$Builder.build(Job.java:186)
```

This seems because com.firebase.jobdispatcher.DefaultJobValidator does not support null values in validateExtrasType, but I think it is a perfectly valid use case.

Here's the code to reproduce:

```
Bundle myExtrasBundle = new Bundle();
myExtrasBundle.putString("test", null);

dispatcher.newJobBuilder()
				.setService(MyService.class)
				.setTag("abc")
				.setRecurring(false)
				.setLifetime(Lifetime.FOREVER)
				.setTrigger(Trigger.executionWindow(0, 60))
				.setReplaceCurrent(true)
				.setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
				.setConstraints(Constraint.ON_ANY_NETWORK)
				.setExtras(myExtrasBundle)
				.build();
```

**Comment by michaeldiener** [comment]
Submitted a fix as pull request:
https://github.com/firebase/firebase-jobdispatcher-android/pull/50
