### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-jobdispatcher-android#51]
```java
public static void start(Team team) {
        Bundle bundle = new Bundle();
        bundle.putParcelable(Constants.INTENT_TEAM, team);

        Job job = BaseHelper.getDispatcher().newJobBuilder()
                .setService(DownloadTeamDataJob.class)
                .setTag(team.getNumber())
                .setExtras(bundle)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .build();
    }

    @Override
    public boolean onStartJob(final JobParameters params) {
        params.getExtras().setClassLoader(Team.class.getClassLoader());
        Team team = params.getExtras().getParcelable(Constants.INTENT_TEAM); // <<Exception
    }
```

I've tried `bundle.setClassLoader(Team.class.getClassLoader());` but that doesn't seem to work.

**Comment by sergeyfitis** [comment]
I have same issue too.

**Comment by SUPERCILEX** [comment]
@ciarand Nope, still seeing it in 0.5.1:
```
12-16 21:38:58.066 2171-3536/? E/AndroidRuntime: FATAL EXCEPTION: netscheduler-queue-handler
                                                 Process: com.google.android.gms.persistent, PID: 2171
                                                 android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.supercilex.robotscouter.data.model.Team
                                                     at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
                                                     at android.os.Parcel.readParcelable(Parcel.java:2462)
                                                     at android.os.Parcel.readValue(Parcel.java:2365)
                                                     at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
                                                     at android.os.BaseBundle.unparcel(BaseBundle.java:269)
                                                     at android.os.BaseBundle.getString(BaseBundle.java:992)
                                                     at qve.<init>(:com.google.android.gms:3113)
                                                     at qve.<init>(:com.google.android.gms:85)
                                                     at qwi.a(:com.google.android.gms:493)
                                                     at qwi.a(:com.google.android.gms:383)
                                                     at qwj.handleMessage(:com.google.android.gms:4048)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by gabrielittner** [comment]
That doesn't look like a issue in jobdispatcher. That stacktrace is from
Play Services and it's process which obviously can't find a that's in your
app. You should generally avoid using custom parcelables in places that
leave your process
https://commonsware.com/blog/2016/07/22/be-careful-where-you-use-custom-parcelables.html

**Comment by SUPERCILEX** [comment]
@gabrielittner I'm not doing anything special. I have a class that implements Parcelable and it works fine from activity to activity. Also, I not putting my service in a different process. The problem is that `GooglePlayReciver` is in it's own process so this is definitely an issue with the library.

**Comment by ciarand** [comment]
This looks like you're trying to put a custom Parcelable in your extras Bundle. There's two problems here:
- Google Play services shouldn't be crashing if it can't unparcel a Parcelable
- The Firebase Job Dispatcher shouldn't allow you to put custom Parcelables in the job's extras Bundle

Either way, this is definitely *not* a supported pattern (as @gabrielittner's link suggests).

**Comment by ciarand** [comment]
It would also be helpful for you to post the exact Google Play services version too, if that's available to you.

**Comment by SUPERCILEX** [comment]
@ciarand my play services:
![screenshot_20161222-151456](https://cloud.githubusercontent.com/assets/9490724/21443362/7a30bd92-c859-11e6-98c1-6903e09053fe.png)

**Comment by ciarand** [comment]
Thanks!
