### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/firebase/jobdispatcher/FirebaseJobDispatcher

### ISSUE THREAD

**Issue by kaiwalyakhasnis** [firebase/firebase-jobdispatcher-android#55]
Crash [run-time]:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/firebase/jobdispatcher/FirebaseJobDispatcher;

My dependencies:
```
// Google Play Services for location
compile 'com.google.android.gms:play-services-location:9.6.1'

compile 'com.firebase:firebase-jobdispatcher:0.5.0'
```

**Comment by SUPERCILEX** [comment]
Try adding this: `compile "com.google.android.gms:play-services-gcm:$playServicesVersion"`. Here's what works for me:
```groovy
compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.0'
compile "com.google.android.gms:play-services-gcm:$playServicesVersion"
```

**Comment by kaiwalyakhasnis** [comment]
Sorry i forgot to mention i could compile it successfully. Mentioned crash is run time exception.

**Comment by SUPERCILEX** [comment]
Oh, then I'm not sure what's going on, but a stack trace would be nice.

**Comment by chrisjenx** [comment]
```
java.lang.RuntimeException: Unable to start service com.firebase.jobdispatcher.GooglePlayReceiver@c78831 with Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.owlr.controller/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.gcm.PendingCallback
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3317)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.gcm.PendingCallback
	at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
	at android.os.Parcel.readParcelable(Parcel.java:2462)
	at android.os.Parcel.readValue(Parcel.java:2365)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
	at android.os.BaseBundle.unparcel(BaseBundle.java:269)
	at android.os.Bundle.getParcelable(Bundle.java:840)
	at com.firebase.jobdispatcher.e.a(SourceFile:40)
	at com.firebase.jobdispatcher.GooglePlayReceiver.a(SourceFile:115)
	at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(SourceFile:83)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3300)
```

1 guess, Play Services 10. Broke this.

**Comment by SUPERCILEX** [comment]
Yeah, you're probably right. Unfortunately, @ciarand isn't the most involved library owner so I don't when this will get fixed. Personally, I'm using the native `JobScheduler` api for anyone on api>21 and this library for people below. Since most of my users are >21 problems with this lib aren't really that big of deal. BTW, [I'm getting a ClassNotFoundException](https://github.com/firebase/firebase-jobdispatcher-android/issues/51) when unmarshalling my parcelable class so this issue probably has something to do with class loaders.
