### ISSUE TITLE
SecurityException: Binder invocation to an incorrect interface

### ISSUE THREAD

**Issue by sytolk** [firebase/firebase-jobdispatcher-android#77]
I have this exception with jobDispatcherVersion = '0.5.0' (I will check with 0.5.2)
```
STACK_TRACE=java.lang.SecurityException: Binder invocation to an incorrect interface
        at android.os.Parcel.readException(Parcel.java:1425)
        at android.os.Parcel.readException(Parcel.java:1379)
        at com.google.android.gms.gcm.c.a(Unknown Source)
        at com.firebase.jobdispatcher.af.a(Unknown Source)
        at com.firebase.jobdispatcher.GooglePlayReceiver.b(Unknown Source)
        at com.firebase.jobdispatcher.aa.a(Unknown Source)
        at com.firebase.jobdispatcher.aa.e(Unknown Source)
        at com.firebase.jobdispatcher.ae.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5435)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)

ANDROID_VERSION=4.2.2
PHONE_MODEL=HM NOTE 1W
```
maybe this is Proguard related ?? this is my proguard gradle:
```
release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```
and proguard-rules.pro
```
-keep class * implements android.os.Parcelable {
     public static final android.os.Parcelable$Creator *;
}
# optimize
-optimizationpasses 2
-optimizations !code/simplification/arithmetic
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
```

**Comment by sytolk** [comment]
I have the same error with different device. But after restart phone this error disappear now and Recurring jobs is working. Maybe this issue is GMS related?? the problem is that if this happened the recurring job is not run.
```java
FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
        Job timeJob = dispatcher.newJobBuilder()
                .setService(TimeJobService.class) // the JobService that will be called
                .setTag("job-tracker")        // uniquely identifies the job
                .setRecurring(true)
                .setLifetime(Lifetime.FOREVER)
                // start between 0 and 60 seconds from now
                .setTrigger(Trigger.executionWindow(1, jobRecurring))
                // overwrite an existing job with the same tag
                .setReplaceCurrent(true)
                .build();
        dispatcher.mustSchedule(timeJob);
```
Stacktrace from Android 6.0.1
```
STACK_TRACE=java.lang.SecurityException: Binder invocation to an incorrect interface
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at com.google.android.gms.gcm.c.a(Unknown Source)
at com.firebase.jobdispatcher.af.a(Unknown Source)
at com.firebase.jobdispatcher.GooglePlayReceiver.b(Unknown Source)
at com.firebase.jobdispatcher.aa.a(Unknown Source)
at com.firebase.jobdispatcher.aa.e(Unknown Source)
at com.firebase.jobdispatcher.ae.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

ANDROID_VERSION=6.0.1
PHONE_MODEL=SM-G935F
```

**Comment by rvenkatsaravanan** [comment]
Still problem exist in newer version, I'm getting this exception while sendMessage using Messenger.
firebase_version: 0.8.5

java.lang.SecurityException: Binder invocation to an incorrect interface
        at android.os.Parcel.nativeEnforceInterface(Native Method)
        at android.os.Parcel.enforceInterface(Parcel.java:610)
        at com.firebase.jobdispatcher.IRemoteJobService$Stub.onTransact(IRemoteJobService.java:47)
        at android.os.Binder.transact(Binder.java:667)
        at android.os.IMessenger$Stub$Proxy.send(IMessenger.java:93)
        at android.os.Messenger.send(Messenger.java:57)

**Comment by z4zzaman** [comment]
> I have this exception with jobDispatcherVersion = '0.5.0' (I will check with 0.5.2)
> 
> ```
> STACK_TRACE=java.lang.SecurityException: Binder invocation to an incorrect interface
>         at android.os.Parcel.readException(Parcel.java:1425)
>         at android.os.Parcel.readException(Parcel.java:1379)
>         at com.google.android.gms.gcm.c.a(Unknown Source)
>         at com.firebase.jobdispatcher.af.a(Unknown Source)
>         at com.firebase.jobdispatcher.GooglePlayReceiver.b(Unknown Source)
>         at com.firebase.jobdispatcher.aa.a(Unknown Source)
>         at com.firebase.jobdispatcher.aa.e(Unknown Source)
>         at com.firebase.jobdispatcher.ae.handleMessage(Unknown Source)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:194)
>         at android.app.ActivityThread.main(ActivityThread.java:5435)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:525)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
>         at dalvik.system.NativeStart.main(Native Method)
> 
> ANDROID_VERSION=4.2.2
> PHONE_MODEL=HM NOTE 1W
> ```
> 
> maybe this is Proguard related ?? this is my proguard gradle:
> 
> ```
> release {
>             minifyEnabled true
>             shrinkResources false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
> ```
> 
> and proguard-rules.pro
> 
> ```
> -keep class * implements android.os.Parcelable {
>      public static final android.os.Parcelable$Creator *;
> }
> # optimize
> -optimizationpasses 2
> -optimizations !code/simplification/arithmetic
> -dontusemixedcaseclassnames
> -dontskipnonpubliclibraryclasses
> ```

You need to give same package name for AIDL file in client-side that have in server-side

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
