### ISSUE TITLE
Error inserting job in Sqlite 

### ISSUE THREAD

**Issue by Arjun-sna** [firebase/firebase-jobdispatcher-android#94]
I'm getting the below log whenever the job is scheduled

> E/SQLiteDatabase: Error inserting source=4 tag=pending-auth-job requires_charging=0 target_package=com.***.*** source_version=0 required_network_type=0 extras={"com.firebase.jobdispatcher.tag":{"pending-auth-job":4},"com.firebase.jobdispatcher.trigger_type":{"1":0},"com.firebase.jobdispatcher.replace_current":{"false":3},"com.firebase.jobdispatcher.persistent":{"2":0},"com.firebase.jobdispatcher.maximum_backoff_seconds":{"3600":0},"com.firebase.jobdispatcher.initial_backoff_seconds":{"30":0},"com.firebase.jobdispatcher.retry_policy":{"1":0},"com.firebase.jobdispatcher.window_end":{"60":0},"com.firebase.jobdispatcher.service":{"com.***.***.jobscheduler.PendingAuthService":4},"com.firebase.jobdispatcher.recurring":{"false":3},"com.firebase.jobdispatcher.constraints":{"2":0},"com.firebase.jobdispatcher.window_start":{"0":0}} flex_time=0 target_class=com.firebase.jobdispatcher.GooglePlayReceiver runtime=1487570616845 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 period=60000 task_type=0 job_id=-1 user_id=0
                                                 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067)
                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1483)
                                                     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1353)
                                                     at rop.a(:com.google.android.gms:337)
                                                     at rou.a(:com.google.android.gms:669)
                                                     at rou.a(:com.google.android.gms:197)
                                                     at rou.a(:com.google.android.gms:179)
                                                     at rom.run(:com.google.android.gms:543)
                                                     at llt.run(:com.google.android.gms:450)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at lqc.run(:com.google.android.gms:17)
                                                     at java.lang.Thread.run(Thread.java:818)
02-20 11:33:36.851 5496-2299/? E/NetworkScheduler: Error persisting task: com.***.***/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="pending-auth-job" trigger=window{start=0s,end=60s,earliest=0s,latest=59s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=0s last_run=N/A jid=N/A status=PENDING retries=0}

Is this the reason for inconsistent start of scheduled jobs?

**Comment by BoondoggleLabs** [comment]
Getting this too:

`Error inserting source=8 tag=background-update2 target_package=****.**** requires_charging=0 source_version=1 required_network_type=2 flex_time=30000 extras={"com.firebase.jobdispatcher.tag":{"background-update2":4},"com.firebase.jobdispatcher.trigger_type":{"1":0},"com.firebase.jobdispatcher.replace_current":{"true":3},"com.firebase.jobdispatcher.persistent":{"2":0},"com.firebase.jobdispatcher.maximum_backoff_seconds":{"3600":0},"com.firebase.jobdispatcher.initial_backoff_seconds":{"30":0},"com.firebase.jobdispatcher.retry_policy":{"1":0},"com.firebase.jobdispatcher.window_end":{"30":0},"com.firebase.jobdispatcher.service":{"****.****":4},"com.firebase.jobdispatcher.recurring":{"false":3},"com.firebase.jobdispatcher.constraints":{"0":0},"com.firebase.jobdispatcher.window_start":{"30":0}} target_class=com.firebase.jobdispatcher.GooglePlayReceiver runtime=1504097379224 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} period=30000 last_runtime=0 task_type=0 job_id=-1 user_id=0`

**Comment by unEgor** [comment]
It means that your job was already presented in the database.
Should be fixed in next release of Google Play Service.

**Comment by tasneembohra** [comment]
I am facing this issue in new release , when we can expect a fix for this ?

**Comment by farrukhnajmi** [comment]
This issue does not say which firebase version it was found in and there is no comment about its resolution though it is closed. Can dev team please tell me how it was resolved? I am encountering it in 11.8.0 on an HTC 1 running Android 6.
